[colors.bright]
black = "#373b41"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.normal]
black = "#282a2e"
blue = "#5f819d"
cyan = "#5e8d87"
green = "#8c9440"
magenta = "#85678f"
red = "#a54242"
white = "#707880"
yellow = "#de935f"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[font]
size = 12.0

[font.bold]
family = "DejaVuSansMono Nerd Font"

[font.italic]
family = "DejaVuSansMono Nerd Font"

[font.normal]
family = "DejaVuSansMono Nerd Font"

[[keyboard.bindings]]
chars = "\u001B[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[9;6u"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "None"
key = "F8"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window.padding]
x = 10
y = 10
